### ISSUE TITLE
useUseWaveSurferRecorder does not exist!

### ISSUE THREAD

**Issue by thatrealal** [meer-sagor/wavesufer-vue#4]
I want to use this library, but when I try to import `useUseWaveSurferRecorder` composeable, it says that the requested module does not provide an export named!

**Comment by meer-sagor** [comment]
Thanks for reporting the issue, I am looking into the matter and will get back to you with an update soon.

**Comment by thatrealal** [comment]
@meer-sagor Sorry for the rush, but would there be any update on this soon?

**Comment by meer-sagor** [comment]
@thatrealal Resolved the issue you mentioned, updated the document, and included a minimum use-case check in the documentation. Keep coding joyfully!

**Comment by nikeshparajuli** [comment]
![CleanShot 2024-04-07 at 12 24 19@2x](https://github.com/meer-sagor/wavesufer-vue/assets/47485043/4d74a34e-cfdb-4b1a-a978-04e82a8eff9e)


Hi @meer-sagor, I'm still experiencing an issue. Am I doing something wrong?

**Comment by nikeshparajuli** [comment]
> import { useWaveSurferRecorder } from '@meersagor/wavesurfer-vue'

This is how I'm importing

**Comment by thatrealal** [comment]
Now I have another issue but with a different error:
`VoiceRecorder.vue:3 Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@meersagor_wavesurfer-vue.js?v=7ebc1108' does not provide an export named 'useWaveSurferRecorder'`

I would be appreciated if you could further investigate on this issue...

**Comment by meer-sagor** [comment]
@thatrealal Thank you for bringing this to my attention. I am currently investigating the matter and will provide you with an update shortly.

**Comment by meer-sagor** [comment]
@nikeshparajuli you are fetching typescript errors. it will be fixed next release. I will try to do the next release ASAP

**Comment by thatrealal** [comment]
I would highly appreciate it if you could update it ASAP, as we need to release it on our side as soon as possible.

**Comment by thatrealal** [comment]
@nikeshparajuli Any news?
