### ISSUE TITLE
good job! but how to set the continuousWaveform = true?

### ISSUE THREAD

**Issue by ctrlaltman** [meer-sagor/wavesufer-vue#8]
like this url: https://wavesurfer.xyz/examples/?record.js  
record = wavesurfer.registerPlugin(
    RecordPlugin.create({
      renderRecordedAudio: false,
      scrollingWaveform,
      continuousWaveform,
      continuousWaveformDuration: 30, // optional
    }),
  )

how to set the continuousWaveform = true?   thanks

**Comment by meer-sagor** [comment]
Hi @ctrlaltman,  

Thank you for reporting the issue! I've reviewed your query and identified the solution. The `recordPluginOptions` configuration supports `continuousWaveform` as well as other options. Here's a minimal example demonstrating how to set it up:  


```javascript
const containerRef = ref<HTMLDivElement | null>(null);

const options = computed(() => ({
    height: 48,
    waveColor: "#66667D",
    progressColor: "#6A24FF",
    barGap: 5,
    barWidth: 5,
    barRadius: 8,
    cursorWidth: 0,
    url: "https://revews-bucket.s3.ap-southeast-1.amazonaws.com/a06mmMU3sgnzuUkH4OiHvyuUgCFdLSnJaDLBao7y.webm",
}));

const { pauseRecording, startRecording, stopRecording, currentTime, isPauseResume } = useWaveSurferRecorder({
    containerRef,
    options: options.value,
    recordPluginOptions: {
      continuousWaveform: true,
      // Add other supported options here as needed
    },
});
```
This setup ensures that `continuousWaveform` and other `recordPluginOptions configurations` are properly applied.

Additionally, please ensure you have updated to the latest version of the package to access this functionality. Feel free to let me know if you encounter any issues or need further assistance!
